estados/config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :statuses
  resources :clients
  resources :companies
  resources :cities
  resources :states
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

estados/app/views/layouts/_alert.html.erb
<br/>
<div class="container">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>

estados/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#2F4F4F;">
  <div class="container-fluid">
    <%= link_to 'States App', root_path , class:"navbar-brand"  %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            States
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown"style="background-color:#DCDCDC;">
            <li><a><%= link_to 'List of States', states_path, class:"dropdown-item" %></a></li>
            <li><a><%= link_to 'Add a State', new_state_path, class:"dropdown-item" %>  </a></li>
      
          </ul>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Cities
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:#DCDCDC;">
            <li><a><%= link_to 'List of Cities', cities_path, class:"dropdown-item" %> </a></li>
            <li><a><%= link_to 'Add a City', new_city_path, class:"dropdown-item" %></a></li>
      
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

estados/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Estates App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body style="background-color:#DCDCDC;">
    <%= render 'layouts/header'%>

    <% if notice %>
      <%= render 'layouts/alert' %>
    <% end %>

    
    <div class="container" >
      <%= yield%>
    </div>

     <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>