estados/config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :statuses
  resources :clients
  resources :companies
  resources :cities
  resources :states
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

estados/app/models/state.rb
class State < ApplicationRecord
    has_many :cities

    
end

estados/app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: %i[ show edit update destroy ]

  # GET /states or /states.json
  def index
    @states = State.all
  end

  # GET /states/1 or /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states or /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to state_url(@state), notice: "State was successfully created." }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to state_url(@state), notice: "State was successfully updated." }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url, notice: "State was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:name)
    end
end

estados/app/helpers/states_helper.rb
module StatesHelper
end

estados/app/views/states/_form.html.erb
<%= form_with(model: state) do |form| %>
  <% if state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
        <% state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3" style="width:50%">
    <%= form.label :name, style: "display: block", class:"form-label" %>
    <%= form.text_field :name , class:"form-control", style:"background-color: #808080; color:#fff"%>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

estados/app/views/states/_state.html.erb
<div id="<%= dom_id state %>">
  <tr>
    <td> <%= state.name %></td>
    <td><%= link_to 'Show', state, class:"btn btn-secondary btn-sm" %></td>
      <td><%= link_to 'Edit', edit_state_path(state),class:"btn btn-secondary btn-sm" %></td>
  </tr>

</div>

estados/app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Show this state", @state, class:"btn btn-secondary", style:"background-color:#2F4F4F" %> |
  <%= link_to "Back to states", states_path, class:"btn btn-secondary" %>
</div>

estados/app/views/states/index.html.erb
<br/>
<h1 class="display-4">State's List</h1>
<br/>
<table class="table table-striped " style="width: 50%;" >

   <thead style="background-color:#708090;">
    <tr >
      <th scope="col" style="color:#fff">Name</th>
      <th colspan="2" style="color:#fff"></th>
    </tr>
  </thead>
  <tbody>
    <% list = @states.sort{|x,y| x[:name] <=> y[:name]}  %>
    <% list.each do |state| %>
      <%= render state %>
    <% end %>
  </tbody>
</table>

<%= link_to "New state", new_state_path, class:"btn btn-secondary", style:"background-color:#2F4F4F" %>

estados/app/views/states/new.html.erb
<br/>
<h1 class="display-4">New state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Back to states", states_path , class:"btn btn-secondary", style:"background-color:#2F4F4F"%>
</div>

estados/app/views/states/show.html.erb
<br/>
<div class="container">
  <h1 class="display-1"><%=@state.name%></h1>
  <br/>
  
    <%list = @state.cities%>

  <% unless list.nil?%>

  <table class="table table-striped " style="width: 50%;" >

   <thead style="background-color:#708090;">
    <tr >
      <th scope="col" style="color:#fff">Cities</th>
      <th colspan="2" style="color:#fff"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
      <% list.each do |city| %>
        <td> <%= city.name %></td>
        <td><%= link_to 'Show', city, class:"btn btn-sm btn-secondary" %></td>
        <td><%= link_to 'Edit', edit_city_path(city),class:"btn btn-sm btn-secondary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%end%>

<div>
  <%= link_to "Edit this state", edit_state_path(@state), class:"btn btn-secondary", style:"background-color:#2F4F4F" %> |
  <%= link_to "Back to states", states_path , class:"btn btn-secondary"%>

  <br/><br/>

  <%= button_to "Destroy this state", @state, method: :delete , class:"btn btn-danger" %>
</div>